SET NOCOUNT ON;
GO
INSERT INTO dbo.netflix (show_id, content_type, title, director, cast_list, country, date_added_raw, release_year, rating, duration_raw, listed_in, description) VALUES (N's1', N'Movie', N'Inception', N'Christopher Nolan', N'Leonardo DiCaprio, Joseph Gordon-Levitt', N'USA', N'01-01-2020', 2010, N'PG-13', N'148 min', N'Sci-Fi, Thriller', N'A thief steals corporate secrets through dream-sharing tech.');
INSERT INTO dbo.netflix (show_id, content_type, title, director, cast_list, country, date_added_raw, release_year, rating, duration_raw, listed_in, description) VALUES (N's2', N'TV Show', N'Stranger Things', N'Unknown', N'Millie Bobby Brown, Finn Wolfhard', N'USA', N'15-07-2016', 2016, N'TV-14', N'3 Seasons', N'Horror, Sci-Fi', N'Kids uncover supernatural mysteries in their town.');
INSERT INTO dbo.netflix (show_id, content_type, title, director, cast_list, country, date_added_raw, release_year, rating, duration_raw, listed_in, description) VALUES (N's3', N'Movie', N'The Irishman', N'Martin Scorsese', N'Robert De Niro, Al Pacino', N'USA', N'27-11-2019', 2019, N'R', N'209 min', N'Crime, Drama', N'Hitman drama revolving around aging mobster life.');
INSERT INTO dbo.netflix (show_id, content_type, title, director, cast_list, country, date_added_raw, release_year, rating, duration_raw, listed_in, description) VALUES (N's4', N'Movie', N'Bird Box', N'Susanne Bier', N'Sandra Bullock, Trevante Rhodes', N'USA', N'21-12-2018', 2018, N'TV-MA', N'124 min', N'Horror, Thriller', N'A mother and her kids try to survive mysterious forces.');
INSERT INTO dbo.netflix (show_id, content_type, title, director, cast_list, country, date_added_raw, release_year, rating, duration_raw, listed_in, description) VALUES (N's5', N'TV Show', N'Dark', N'Unknown', N'Louis Hofmann, Lisa Vicari', N'Germany', N'01-12-2017', 2017, N'TV-MA', N'3 Seasons', N'Sci-Fi, Mystery', N'A boy investigates a time-travel conspiracy.');
INSERT INTO dbo.netflix (show_id, content_type, title, director, cast_list, country, date_added_raw, release_year, rating, duration_raw, listed_in, description) VALUES (N's6', N'Movie', N'Extraction', N'Sam Hargrave', N'Chris Hemsworth, Rudhraksh Jaiswal', N'USA', N'07-04-2020', 2020, N'R', N'117 min', N'Action, Thriller', N'A black-market mercenary embarks on a deadly mission.');
INSERT INTO dbo.netflix (show_id, content_type, title, director, cast_list, country, date_added_raw, release_year, rating, duration_raw, listed_in, description) VALUES (N's7', N'TV Show', N'Money Heist', N'Unknown', N'Ãšrsula CorberÃ³, Ãlvaro Morte', N'Spain', N'01-05-2017', 2017, N'TV-MA', N'5 Seasons', N'Crime, Thriller', N'Robbers plan heists led by The Professor.');
INSERT INTO dbo.netflix (show_id, content_type, title, director, cast_list, country, date_added_raw, release_year, rating, duration_raw, listed_in, description) VALUES (N's8', N'Movie', N'The Old Guard', N'Gina Prince-Bythewood', N'Charlize Theron, KiKi Layne', N'USA', N'10-07-2020', 2020, N'R', N'125 min', N'Action, Fantasy', N'A warrior leads an immortal group in combat.');
INSERT INTO dbo.netflix (show_id, content_type, title, director, cast_list, country, date_added_raw, release_year, rating, duration_raw, listed_in, description) VALUES (N's9', N'Movie', N'Enola Holmes', N'Harry Bradbeer', N'Millie Bobby Brown, Henry Cavill', N'UK', N'23-09-2020', 2020, N'PG-13', N'123 min', N'Mystery, Adventure', N'Teen detective solves a royal mystery.');
INSERT INTO dbo.netflix (show_id, content_type, title, director, cast_list, country, date_added_raw, release_year, rating, duration_raw, listed_in, description) VALUES (N's10', N'TV Show', N'Lucifer', N'Unknown', N'Tom Ellis, Lauren German', N'USA', N'01-01-2016', 2016, N'TV-14', N'6 Seasons', N'Fantasy, Crime', N'A devil works with LAPD to punish criminals.');
